version: '3'
services:
  gondolin-postgis:
    image: mdillon/postgis:10-alpine
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: gondolin
      POSTGRES_PASSWORD: gondolin
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data:Z
  gondolin-pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DEFAULT_EMAIL: admin